Макет экрана Выбор места работы
sobolevkir/JobCraft pull request #114
Opened 2024-10-12 19:07 UTC by A2T-user

Макет экрана Выбор места работы

2024-10-13 13:38 UTC, Yuliya-Sycheva requested changes

2024-10-13 13:38 UTC, Yuliya-Sycheva commented on app/src/main/res/layout/fragment_select_place.xml
> +                android:textSize="50sp"
Размер нужно убрать, это ты мне, наверно, про стили объяснял))

2024-10-13 14:09 UTC, Yuliya-Sycheva requested changes

2024-10-13 14:09 UTC, Yuliya-Sycheva commented on app/src/main/res/drawable/blue_rectangle.xml
> +</shape>
Андрей, у меня уже есть такой элемент, он влит в ветку develop. Замержи к себе в ветку обновленную ветку develop, свой удали, используй мой

2024-10-13 14:09 UTC, Yuliya-Sycheva commented on app/src/main/res/drawable/ic_arrow_forward.xml
> +      android:fillColor="@color/gray"/>
это тоже добавляла уже, уже есть в develop, возьми готовый

2024-10-14 09:55 UTC, A2T-user commented on app/src/main/res/drawable/ic_arrow_forward.xml
> +      android:fillColor="@color/gray"/>
Оставил свою иконку. Почему - написал тебе в пачку

2024-10-14 09:55 UTC, A2T-user commented on app/src/main/res/drawable/blue_rectangle.xml
> +</shape>
Взял твою плашку

2024-10-14 09:55 UTC, A2T-user commented on app/src/main/res/layout/fragment_select_place.xml
> +                android:textSize="50sp"
Именно так все и было. Убрал

2024-10-14 10:14 UTC, sobolevkir approved these changes

2024-10-14 10:19 UTC, merged