PR_Epic1_49_vacancy search UI toolbar edittext recyclerview mistakes
sobolevkir/JobCraft pull request #54
Opened 2024-10-04 21:57 UTC by Yuliya-Sycheva

2024-10-04 22:10 UTC, Why-Man55 commented on app/src/main/res/drawable/ic_cover_placeholder.xml
> +        android:fillType="evenOdd"
Тут забыла цвет из ресурсов взять

2024-10-05 11:17 UTC, sobolevkir requested changes
Посмотри пожалуйста комментарии, давай сегодня всё это исправим)

2024-10-05 11:17 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
> +        binding.toolbar.setOnClickListener {
не стоит так делать на мой взгляд. ClickListener на элементы списка сделает Марат, а вот про ClickListener на Toolbar он может не обратить внимание и в приложении будет баг..

2024-10-05 11:17 UTC, sobolevkir commented on app/src/main/res/layout/fragment_search.xml
1. Давай сделаем через CoordinatorLayout прилипание надписи с количеством найденных вакансий.
2. Давай сделаем ошибку как одну TextView с надписью и картинкой.

Вот мой пример из PlaylistMaker'а, который заменяет все блоки с кодом ошибки из твоего кода:

 ```
<TextView
        android:id="@+id/tv_error_message"
        style="@style/ErrorMessageStyle"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="@string/error_connection_problem"
        android:visibility="gone" />
```
        
 А это стиль этого TextView:
 
  ```
<style name="ErrorMessageStyle">
        <item name="android:layout_marginTop">@dimen/special_element_top_indent</item>
        <item name="android:layout_marginHorizontal">@dimen/large_indent</item>
        <item name="android:gravity">center</item>
        <item name="android:textAppearance">@style/YS_Medium_19</item>
        <item name="android:textColor">?attr/colorOnBackground</item>
        <item name="drawableTopCompat">@drawable/nothing_found</item>
        <item name="android:drawablePadding">@dimen/standard_indent</item>
    </style>
```

2024-10-05 11:17 UTC, sobolevkir commented on .kotlin/sessions/kotlin-compiler-10595687168518545818.salive
удаляем этот файл)

2024-10-05 13:41 UTC, danil377377 approved these changes
молодец, у меня нет замечаний. Как сделаешь мёрдж буду твой стиль использовать

2024-10-05 18:50 UTC, sobolevkir approved these changes

2024-10-05 18:59 UTC, merged