PR_Epic1_64_dto_data_class_converter
sobolevkir/JobCraft pull request #65
Opened 2024-10-06 13:32 UTC by Yuliya-Sycheva

2024-10-06 14:17 UTC, sobolevkir requested changes

2024-10-06 14:17 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/search/data/dto/LogoUrlsDto.kt
> +    @SerializedName("240") val logoUrl: String?
лучше написать logoUrl240

2024-10-06 14:17 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/search/data/mapper/Mapper.kt
> +class Mapper {
я согласен уже на Object тут и нужно ему более подробное имя дать, например VacancyMapper

2024-10-06 14:17 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchResponse.kt
> +    @SerializedName("per_page") val perPage: Int,
per_page здесь не нужен по идее, т.к. у нас уже будет запрос с указанием данного параметра. Поэтому мы его заранее сами задаём и знаем.

2024-10-07 07:03 UTC, Why-Man55 approved these changes

2024-10-07 07:22 UTC, sobolevkir approved these changes

2024-10-07 07:22 UTC, merged