Epic3 44 favorites screen
sobolevkir/JobCraft pull request #68
Opened 2024-10-07 21:41 UTC by danil377377

Эта ветка продолжение пулла про дата слой. Дата слой уже не актуален. В последнем коммите в комментарии указал как мою работу могут использовать в фиче экрана поиска и деталей вакансии

2024-10-08 14:37 UTC, A2T-user commented on app/src/main/java/ru/practicum/android/diploma/common/ui/VacancyListAdapter.kt
> +        with(holder) {
Не понял. Зачем нужен with?

2024-10-08 14:37 UTC, A2T-user commented on app/src/main/java/ru/practicum/android/diploma/common/ui/VacancyListAdapter.kt
> +        val layoutInspector = LayoutInflater.from(parent.context)
Может не layoutInspector, а layoutInflater

2024-10-08 14:44 UTC, danil377377 commented on app/src/main/java/ru/practicum/android/diploma/common/ui/VacancyListAdapter.kt
> +        with(holder) {
чтобы не повторять многократно holder. без with будет
 `
        holder.bind(vacancies[position])
        holder.binding.root.setOnClickListener { onItemClick(vacancies[position]) }
        holder.binding.root.setOnLongClickListener {
                onItemLongClick?.invoke(vacancies[position])?.let { true } ?: false
            }`

2024-10-08 14:45 UTC, danil377377 commented on app/src/main/java/ru/practicum/android/diploma/common/ui/VacancyListAdapter.kt
> +        val layoutInspector = LayoutInflater.from(parent.context)
согласен, поменяю

2024-10-08 14:53 UTC, A2T-user commented on app/src/main/java/ru/practicum/android/diploma/favorites/data/converter/FavoriteVacancyDbConverter.kt
>          favoriteVacancyEntity.name,
@Ты в курсе, что Кирилл уже переделал Salary в VacancyDetails в String? И Address то же, только keySkills не захотел
Сделай пожалуйста обратную конвертацию из VacancyDetails в FavoriteVacancyEntity мне ведь вакансии и обновлять и добавлять придется
Может быть сделать перегруженный метод - одинаковое название (convert или map) с разными аргументами? Мне кажется было бы удобно.

2024-10-08 14:55 UTC, A2T-user commented on app/src/main/java/ru/practicum/android/diploma/common/ui/VacancyListAdapter.kt
> +        with(holder) {
Я такого применения еще не видел. Круто

2024-10-08 16:03 UTC, danil377377 commented on app/src/main/java/ru/practicum/android/diploma/favorites/data/converter/FavoriteVacancyDbConverter.kt
>          favoriteVacancyEntity.name,
сделал

2024-10-08 17:33 UTC, Yuliya-Sycheva requested changes

2024-10-08 17:33 UTC, Yuliya-Sycheva commented on app/src/main/java/ru/practicum/android/diploma/common/ui/VacancyListAdapter.kt
> +            onItemClick
Здесь не нужно item передать - onItemClick(item)?

2024-10-08 17:33 UTC, Yuliya-Sycheva commented on app/src/main/java/ru/practicum/android/diploma/favorites/data/entity/FavoriteVacancyEntity.kt
> +    val keySkills: String?,
Лишний ?, там не будет null: в VacancyDetails его нет и в документации

2024-10-08 17:33 UTC, Yuliya-Sycheva commented on app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesFragment.kt
> +            tvErrorText.text = "Список пуст"
Здесь и в аналогичных случаях нужно использовать строковые ресурсы.

2024-10-08 17:33 UTC, Yuliya-Sycheva commented on app/src/main/java/ru/practicum/android/diploma/vacancy/ui/VacancyFragment.kt
> +        binding.txHeader.text = "id = $args"
не забыть потом убрать

2024-10-08 17:33 UTC, Yuliya-Sycheva commented on app/src/main/res/layout/fragment_favorites.xml
> +            android:visibility="gone" />
это лишнее, нужно первую ImageView использовать для двух разных состояний и задавать разную картинку: список пуст или нет вакансий. Имя лучше исправить на  iv_error, например

2024-10-08 18:27 UTC, A2T-user reviewed
Мне все понравилось

2024-10-08 23:11 UTC, Yuliya-Sycheva commented on app/src/main/java/ru/practicum/android/diploma/common/ui/VacancyListViewHolder.kt
> +            .into(binding.ivVacancyCover)
Для правильно отображения иконки исправить Glide так:
```
Glide.with(binding.root)
            .load(vacancy.employerLogoUrl240)
            .centerInside()
            .centerCrop()
            .placeholder(R.drawable.ic_cover_placeholder)
            .transform(RoundedCorners(cornerRadius))
            .apply(RequestOptions().transform(RoundedCorners(cornerRadius)))
            .into(binding.ivVacancyCover)
```

необходимый импорт: `import com.bumptech.glide.request.RequestOptions`

2024-10-08 23:11 UTC, Yuliya-Sycheva commented on app/src/main/res/values/dimens.xml
> +    <dimen name="radius_small">2dp</dimen>
Исправить на 12dp для правильного отображения иконки
(остальные настройки для отображения иконки внесу в другие файлы сама)

2024-10-09 10:32 UTC, sobolevkir requested changes

2024-10-09 10:32 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/favorites/data/converter/FavoriteVacancyDbConverter.kt
> +class FavoriteVacancyDbConverter : KoinComponent {
здесь можно внедрить gson через коин-модуль напрямую в конструктор, т.е. лучше напиши
```suggestion
class FavoriteVacancyDbConverter (gson: Gson) {
```
и не нужно будет наследовать класс от KoinComponent и прописывать val в теле класса

2024-10-09 10:32 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/favorites/data/dao/FavoriteVacancyDao.kt
> +package ru.practicum.android.diploma.favorites.data.dao
может всё же оставим этот интерфейс в common?
Его же ещё Андрей использует в своей фиче.
Когда всё сольём, будет путаница..

2024-10-09 10:32 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/favorites/presentation/FavoritesViewModel.kt
> +        val vacancyTestList = listOf(
этот тест сейчас уже не нужен наверное?

2024-10-09 10:32 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesFragment.kt
> +    private var isClickAllowed = true
давай используем для debounce утилиту-функцию, которую я заранее создал в пакете common.
Вот пример реализации дебаунс-метода во фрагменте:
![image](https://github.com/user-attachments/assets/c87e753e-3470-4526-a5e8-c12fc6cda350)

2024-10-09 10:32 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesFragment.kt
> +        val action = FavoritesFragmentDirections.actionFavoritesFragmentToVacancyFragment(vacancy.id)
идеально) только лучше сразу в метод vacancy.id передать, а не всю vacancy)

2024-10-09 10:32 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/vacancy/ui/VacancyFragment.kt
> +        binding.txHeader.text = "id = $args"
лучше сразу убрать.

2024-10-09 10:39 UTC, danil377377 commented on app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesFragment.kt
> +    private var isClickAllowed = true
Я пробовал. Детект ругался. Говорил lateinit нужно убрать

2024-10-09 12:52 UTC, sobolevkir approved these changes

2024-10-09 12:52 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesFragment.kt
> +    private var isClickAllowed = true
Хорошо ,тогда давай оставим старый метод.
Удали тогда пожалуйста debounce-утилиту.

2024-10-09 16:04 UTC, merged