PR_Epic1_39_search_domain
sobolevkir/JobCraft pull request #69
Opened 2024-10-08 00:56 UTC by Why-Man55

2024-10-08 19:33 UTC, Yuliya-Sycheva requested changes
Не знала, что пока нельзя проверять, оставляю комментарии, которые успела написать)

2024-10-08 19:33 UTC, Yuliya-Sycheva commented on app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
> +    single<VacanciesInteractor>{
Лучше заменить на factory, интерактор - не сильно нагруженный класс

2024-10-08 19:33 UTC, Yuliya-Sycheva commented on app/src/main/java/ru/practicum/android/diploma/search/domain/impl/VacanciesInteractorImpl.kt
> +        return repository.searchVacancies(mapOf(Pair(options.request, "${options.page}"))).map { result ->
более читаемо, мне кажется, так:  `mapOf(Pair(options.request, options.page.toString()))`, но можно и не править)

2024-10-09 15:04 UTC, sobolevkir commented on app/src/main/java/ru/practicum/android/diploma/search/domain/impl/VacanciesInteractorImpl.kt
> +        return repository.searchVacancies(mapOf(Pair(options.request, "${options.page}"))).map { result ->
> более читаемо, мне кажется, так: `mapOf(Pair(options.request, options.page.toString()))`, но можно и не править)

В этом как раз у нас ошибка, т.к. серверу нужны required-значения, а мы ему только 2 из 3х передаём...

2024-10-09 15:07 UTC, sobolevkir requested changes
Предложение объединить все состояния экрана поиска в sealed interface, а для определения ошибки пользоваться ErrorType - в данном классе есть все возможные виды ошибок для нашего случая. От множества констант в компаньоне можно будет избавиться. Так код станет чище и понятнее.

2024-10-09 20:36 UTC, merged